version: '4.0'

services:
  form-vite:
    image: ghcr.io/conicuznhm/form-vite:2  # need to comment object build if want to make pull this image
    # //uncomment object build if you want to build the image locally, the image will tag and name ghcr.io/conicuznhm/form-vite:2
    # build:  
    #   context: ./fill-vite
    #   dockerfile: Dockerfile
    container_name: form-vite
    networks:
      - form-network
    ports:
      - "8888:80"
    depends_on:
      form-api:
        condition: service_healthy
    restart: unless-stopped

  form-api:
    image: ghcr.io/conicuznhm/form-api:2  # need to comment object build if want to make pull this image
    # //uncomment object build if you want to build the image locally, the image will tag and name ghcr.io/conicuznhm/form-api:2
    # build:  
    #   context: ./fill-api
    #   dockerfile: Dockerfile
    container_name: form-api
    env_file:
      - ./fill-api/.env.local
    # //Alternatively, set environment variables explicitly (uncomment if not using .env.local)
    # environment:
    #   - DATABASE_URL=postgresql://postgres:password@form-psql:5432/form_db
    #   - PORT=8899
    networks:
      - form-network
    ports:
      - "8899:8899"
    depends_on:
      form-psql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet --tries=1 --timeout=2 http://localhost:8899/health || exit 1"]
      # test: ["CMD-SHELL", "curl -f http://localhost:8899/health || exit 1"]     # //if curl is installed
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  form-psql:
    image: postgres:17.5  # or full path for podman : docker.io/library/postgres:17.5
    container_name: form-psql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=form_db
    volumes:
      - fill-data:/var/lib/postgresql/data
    networks:
      - form-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  form-network:
    name: form-network
    # external: true   # use existing network

volumes:
  fill-data:
    name: fill-data
    # external: true   # use existing volume