---
# secret for database psql
apiVersion: v1
kind: Secret
metadata:
  name: form-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # base64 encoded 'postgres'
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64 encoded 'password'
  POSTGRES_DB: Zm9ybV9kYg==  # base64 encoded 'form_db'
---
# secret for database url
apiVersion: v1
kind: Secret
metadata:
  name: db-url-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBzcWwtc2VydmljZTo1NDMyL2Zvcm1fZGI=  # base64 encoded 'postgresql://postgres:password@psql-service:5432/form_db'
---