---
# secret for database psql
apiVersion: v1
kind: Secret
metadata:
  name: form-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # base64 encoded 'postgres'
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64 encoded 'password'
  POSTGRES_DB: Zm9ybV9kYg==  # base64 encoded 'form_db'
---