---
# vite deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-vite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form-vite
  template:
    metadata:
      labels:
        app: form-vite
    spec:
      initContainers:
        - name: wait-for-api
          image: busybox:1.36
          # command: ['sh', '-c', 'until nc -z form-api.default.svc.cluster.local 8899; do echo "Waiting for form-api..."; sleep 2; done']
          command: ['sh', '-c']
          args:
            - |
              TIMEOUT=60; \
              COUNT=0; \
              echo "Waiting for form-api to be ready..."; \
              until nc -z form-api.default.svc.cluster.local 8899; do \
                echo "form-api is not ready yet, Waiting..."; \
                sleep 2; \
                COUNT=$((COUNT + 2)); \
                if [ $COUNT -ge $TIMEOUT ]; then \
                  echo "Timeout waiting for form-api after ${TIMEOUT} seconds"; \
                  exit 1; \
                fi; \
              done; \
              echo "form-api is up! - continuing..."
      containers:
        - name: form-vite
          image: ghcr.io/conicuznhm/form-vite:1.0.8
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: ghcr-secret # credential for pulling image from private registry
      # restartPolicy: Always # always restart the container if it fails, for development only Always is allowed and automatically default set by kubernetes
---
# vite service
apiVersion: v1
kind: Service
metadata:
  name: form-vite
spec:
  type: ClusterIP
  selector:
    app: form-vite # selector must match app label in deployment template metadata (labels: app: form-vite)
  ports:
    - protocol: TCP
      port: 80 # port of the service
      targetPort: 80 # target port of the container
---